networks:
  core_networks:
    driver: bridge

version: "3.8"
services:
  core:
    image: postgres:latest
    container_name: core
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: core
        POSTGRES_PASSWORD: core
        POSTGRES_DB: core
    networks:
      - core_networks

  iam_core:
    image: postgres:latest
    container_name: iam_core
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: iam_core
      POSTGRES_PASSWORD: iam
      POSTGRES_DB: iam
    networks:
      - core_networks





